In [55]:
# %pip install pandas

In [56]:
import pandas as pd

# Create a DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "Salary": [50000, 60000, 70000, 80000],
}

df = pd.DataFrame(data)

# Display the DataFrame
print("DataFrame:")
print(df)

# Select a column
print("\nNames:")
print(df["Name"])

# Filter rows
print("\nEmployees with salary > 60000:")
print(df[df["Salary"] > 60000])

# Calculate average salary
average_salary = df["Salary"].mean()
print("\nAverage Salary:", average_salary)

DataFrame:
      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    David   40   80000

Names:
0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: str

Employees with salary > 60000:
      Name  Age  Salary
2  Charlie   35   70000
3    David   40   80000

Average Salary: 65000.0

In [57]:
df.describe()

             Age        Salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000

In [58]:
df = pd.read_csv("customers_tiny - customers_tiny.csv")

In [59]:
df.head()

    age     city  score  purchased
0  22.0  Colombo   0.81          1
1  35.0    Kandy   0.44          0
2  28.0    Galle    NaN          1
3  41.0  Colombo   0.67          1
4   NaN    Kandy   0.55          0

In [60]:
# pd.iloc[[rows],[cols]]
# display(pd.iloc[[1:2, 1:3]])

In [61]:
# city = Colombo and score > 0.5

filtered_df = df[(df["city"] == "Colombo") & (df["score"] > 0.5)]
display(filtered_df)

    age     city  score  purchased
0  22.0  Colombo   0.81          1
3  41.0  Colombo   0.67          1

In [62]:
df

    age     city  score  purchased
0  22.0  Colombo   0.81          1
1  35.0    Kandy   0.44          0
2  28.0    Galle    NaN          1
3  41.0  Colombo   0.67          1
4   NaN    Kandy   0.55          0
5  33.0    Galle   0.90          1

In [63]:
# Handling null empty values

# Fill missing values in Age with the mean
# df["age"] = df["age"].fillna(df["age"].mean())

# Fill missing values in Score with the median
# df["score"] = df["score"].fillna(df["score"].median())


# more compact form
df.fillna({"age": df["age"].mean(), "score": df["score"].median()}, inplace=True)

    age     city  score  purchased
0  22.0  Colombo   0.81          1
1  35.0    Kandy   0.44          0
2  28.0    Galle   0.67          1
3  41.0  Colombo   0.67          1
4  31.8    Kandy   0.55          0
5  33.0    Galle   0.90          1

In [64]:
# Converting data types
df["age"] = df["age"].astype(int)
print(df.dtypes)

age            int64
city             str
score        float64
purchased      int64
dtype: object

In [65]:
# Sort by score ase
df.sort_values(by="score", ascending=True, inplace=True)

In [66]:
df

   age     city  score  purchased
1   35    Kandy   0.44          0
4   31    Kandy   0.55          0
3   41  Colombo   0.67          1
2   28    Galle   0.67          1
0   22  Colombo   0.81          1
5   33    Galle   0.90          1

In [ ]:
# Add a new column named distance
df["distance"] = [10, 20, 30, 40, 50, 60]
df

   age     city  score  purchased  distance
1   35    Kandy   0.44          0        10
4   31    Kandy   0.55          0        20
3   41  Colombo   0.67          1        30
2   28    Galle   0.67          1        40
0   22  Colombo   0.81          1        50
5   33    Galle   0.90          1        60

In [68]:
#  Add new row 
df.loc[len(df)] = {
    "age": 25,
    "score": 90.0,
    "purchased": 0,
    "distance": 70,
    "city": "Panadura",
}
df

   age      city  score  purchased  distance
1   35     Kandy   0.44          0        10
4   31     Kandy   0.55          0        20
3   41   Colombo   0.67          1        30
2   28     Galle   0.67          1        40
0   22   Colombo   0.81          1        50
5   33     Galle   0.90          1        60
6   25  Panadura  90.00          0        70

In [69]:
# Group by
print(df.groupby("city")["score"].mean())

city
Colombo      0.740
Galle        0.785
Kandy        0.495
Panadura    90.000
Name: score, dtype: float64

In [71]:
# Group by multiple columns and aggregate
df.groupby('city').agg(
    avg_score =('score', 'mean'),
    total_purchased =('purchased', 'sum'),
    avg_age =('age', 'mean')
)

          avg_score  total_purchased  avg_age
city
Colombo       0.740                2     31.5
Galle         0.785                2     30.5
Kandy         0.495                0     33.0
Panadura     90.000                0     25.0